name: Lint Checks
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.15'
          architecture: 'x64'
      - name: Install dependencies
        run: pip install -r requirements_dev.txt; pip install -r requirements.txt
        shell: bash
      - name: Run pylint checks
        run: pylint src --rcfile=.pylintrc
